### ISSUE TITLE
conflicts pytorch version  

### ISSUE THREAD

**Issue by yeetan** [akanazawa/human_dynamics#60]
AlphaPose requires PyTorch > 1.1, but HMMR needs Pytorch 0.4.0, now my AlphaPose seems to get some error like "ImportError: cannot import name 'Optional" in Pytroch 0.4.0.

**Comment by yeetan** [comment]
I have a workaround, create two anaconda environments:   hmr0 with PyTorch 0.4.0 and hmr1 with PyTorch 1.1.1,  first, use FFmpeg to create images, then use a command to run AlphaPose to create track result json, then run PoseFlow/track-general.py, finally, in hmr0 generate the predicts.

**Comment by jasonyzhang** [comment]
That works fine, but if you want to avoid swapping between environments, you can use the AlphaPose fork in our README which should work with Pytorch 0.4.0.

Alternatively, if you want to keep the newer improvements in AlphaPose, you can update to the latest version of Pytorch if you also upgrade NMR to the latest commit. I believe there's only a one line change to make our code support the newer NMR API (see #17).

Best,
Jason
